# Frontend stage 1
FROM node:15-alpine3.13 as node
WORKDIR /home/app

COPY ./client .
RUN \
  npm install && \
  npm run build

#Frontend stage 2
FROM nginx:1.19-alpine

COPY --from=node /home/app/dist/set /usr/share/nginx/html
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8082

CMD "nginx -g 'daemon off;'"