FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

COPY ./server .
RUN dotnet restore set.api/set.api.sln
RUN dotnet publish set.api/set.api.sln -c Release -o /app --no-restore
EXPOSE 80

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /source ./
ENTRYPOINT ["dotnet", "./set.api/bin/Release/net5.0/set.api.dll"]